# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_description_dises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description_dises',
            old_name='update',
            new_name='updated',
        ),
    ]
